# Generated by Django 4.1.3 on 2022-11-25 19:46

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=200)),
                ("cook_time", models.CharField(default="", max_length=10)),
                ("ingredients", models.TextField()),
                ("steps", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "preview",
                    models.ImageField(null=True, upload_to="../frontend/static/images"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=models.SET(api.models.get_default_recipe_category),
                        to="api.category",
                    ),
                ),
            ],
        ),
    ]
