# Generated by Django 4.1.3 on 2022-11-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="steps",
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="preview",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
