# Generated by Django 4.1.3 on 2022-11-29 12:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_recipe_ingredients_remove_recipe_steps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="steps",
            field=ckeditor.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
