# Generated by Django 4.1.3 on 2022-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_recipe_ingredients_recipe_steps"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="preview",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
